sudo: required
dist: trusty
script:
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="~/miniconda/bin:$PATH"
- source ~/.bashrc
- conda env create -f environment.yml
- conda activate myenv -y
- snakemake
branches:
  only:
    - master
notifications:
  pushover:
    api_key: $PUSHOVER_API
    users:
      - $PUSHOVER_USER

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
      branch: master
