sudo: required
dist: trusty
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
- bash ~/miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda3/bin:$PATH"
- conda env create -f environment.yml
- conda activate tectonic-env
script:
- snakemake
branches:
  only:
    - master
notifications:
  pushover:
    api_key: $PUSHOVER_API
    users: $PUSHOVER_USER

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
      branch: master
