theme: jekyll-theme-cayman
markdown: kramdown
exclude:
  - CNAME
  - README
  - "*.tex"
title: gitMechanics
description: Open-source Mechanics Knowledge-base
markdown: kramdown
google_analytics: UA-127468533-1
repository: gitMechanics