theme: jekyll-theme-cayman
title: Civil Engineering Learning Material
description: Civil Engineering Undergraduate Student Building Learning Content
markdown: kramdown
exclude:
  - CNAME
  - README
  - "*.tex"